# Documentation: https://github.com/roots/trellis#wordpress-sites
mysql_root_password: devpw
mailhog_install_ssmtp: no

web_user: vagrant

wordpress_sites:
  www.tastingroomdelmar.com:
    site_hosts:
      - tr.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:discreteunits/freealty.com.git 
    site_install: true
    site_title: Tasting Room Del Mar
    admin_user: admin
    admin_password: admin
    admin_email: ryan.espinoza@discreteunits.com
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://tr.dev
      wp_siteurl: http://tr.dev/wp
      wp_env: development
      db_name: tr_dev
      db_user: tr_dbuser
      db_password: tr_dbpassword

mail_smtp_server: localhost:1025
mail_admin: admin@freealty.com
mail_hostname: tastingroomdelmar.com
ssmtp_auth_method: ""
ssmtp_start_tls: 'no'
ssmtp_tls: 'no'

# ferm_enabled: false

php_error_reporting: 'E_ALL'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_track_errors: 'On'
php_mysqlnd_collect_memory_statistics: 'On'
php_opcache_enable: 0

xdebug_install: false
php_xdebug_remote_enable: true
php_xdebug_remote_connect_back: true
php_xdebug_remote_host: localhost
php_xdebug_remote_port: 9000
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_idekey: XDEBUG
php_max_nesting_level: 200